-- Pre-populate all 50 US states as drafts, so a national admin only has to
-- launch (not manually type in) the ones they're ready to go live with.
-- on conflict do nothing keeps this safe to re-run.
insert into states (name, slug, abbreviation) values
  ('Alabama', 'alabama', 'AL'),
  ('Alaska', 'alaska', 'AK'),
  ('Arizona', 'arizona', 'AZ'),
  ('Arkansas', 'arkansas', 'AR'),
  ('California', 'california', 'CA'),
  ('Colorado', 'colorado', 'CO'),
  ('Connecticut', 'connecticut', 'CT'),
  ('Delaware', 'delaware', 'DE'),
  ('Florida', 'florida', 'FL'),
  ('Georgia', 'georgia', 'GA'),
  ('Hawaii', 'hawaii', 'HI'),
  ('Idaho', 'idaho', 'ID'),
  ('Illinois', 'illinois', 'IL'),
  ('Indiana', 'indiana', 'IN'),
  ('Iowa', 'iowa', 'IA'),
  ('Kansas', 'kansas', 'KS'),
  ('Kentucky', 'kentucky', 'KY'),
  ('Louisiana', 'louisiana', 'LA'),
  ('Maine', 'maine', 'ME'),
  ('Maryland', 'maryland', 'MD'),
  ('Massachusetts', 'massachusetts', 'MA'),
  ('Michigan', 'michigan', 'MI'),
  ('Minnesota', 'minnesota', 'MN'),
  ('Mississippi', 'mississippi', 'MS'),
  ('Missouri', 'missouri', 'MO'),
  ('Montana', 'montana', 'MT'),
  ('Nebraska', 'nebraska', 'NE'),
  ('Nevada', 'nevada', 'NV'),
  ('New Hampshire', 'new-hampshire', 'NH'),
  ('New Jersey', 'new-jersey', 'NJ'),
  ('New Mexico', 'new-mexico', 'NM'),
  ('New York', 'new-york', 'NY'),
  ('North Carolina', 'north-carolina', 'NC'),
  ('North Dakota', 'north-dakota', 'ND'),
  ('Ohio', 'ohio', 'OH'),
  ('Oklahoma', 'oklahoma', 'OK'),
  ('Oregon', 'oregon', 'OR'),
  ('Pennsylvania', 'pennsylvania', 'PA'),
  ('Rhode Island', 'rhode-island', 'RI'),
  ('South Carolina', 'south-carolina', 'SC'),
  ('South Dakota', 'south-dakota', 'SD'),
  ('Tennessee', 'tennessee', 'TN'),
  ('Texas', 'texas', 'TX'),
  ('Utah', 'utah', 'UT'),
  ('Vermont', 'vermont', 'VT'),
  ('Virginia', 'virginia', 'VA'),
  ('Washington', 'washington', 'WA'),
  ('West Virginia', 'west-virginia', 'WV'),
  ('Wisconsin', 'wisconsin', 'WI'),
  ('Wyoming', 'wyoming', 'WY')
on conflict (slug) do nothing;
